config/routes.rb
Rails.application.routes.draw do
  get 'home/about'
  get 'home/index'
  get 'pokemons/search'
  resources :pokemon_moves
  resources :pokemon_abilities
  resources :pokemon_types
  resources :moves
  resources :abilities
  resources :types
  resources :sprites
  resources :pokemons
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/ability.rb
class Ability < ApplicationRecord
  validates :id, :name, :effect, presence: true
  validates :id, :name, uniqueness: true

  has_many :pokemon_abilities
  has_many :pokemon, through: :pokemon_abilities
  paginates_per 25
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/move.rb
class Move < ApplicationRecord
  validates :id, :name, :pp, presence: true
  validates :id, :name, uniqueness: true

  has_many :pokemon_moves
  has_many :pokemon, through: :pokemon_moves

  paginates_per 50
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  validates :id, :name, :baseExperience, :hp, :attack, :defense, :specialAttack, :specialDefense, :speed, :weight, :height, presence: true
  validates :id, :name, uniqueness: true

  has_many :pokemon_types
  has_many :types, through: :pokemon_types

  has_many :pokemon_abilites
  has_many :abilites, through: :pokemon_abilities

  has_many :pokemon_moves
  has_many :moves, through: :pokemon_moves

  paginates_per 25
end

app/models/pokemon_ability.rb
class PokemonAbility < ApplicationRecord
  belongs_to :pokemon
  belongs_to :ability
end

app/models/pokemon_move.rb
class PokemonMove < ApplicationRecord
  belongs_to :pokemon
  belongs_to :move
end

app/models/pokemon_type.rb
class PokemonType < ApplicationRecord
  belongs_to :pokemon
  belongs_to :type
end

app/models/sprite.rb
class Sprite < ApplicationRecord
  belongs_to :pokemon
end

app/models/type.rb
class Type < ApplicationRecord
  validates :id, :name, presence: true
  validates :id, :name, uniqueness: true

  has_many :pokemon_types
  has_many :pokemon, through: :pokemon_types
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
  end

  def index
  end

  def search

  end

  def results
    @results = Pokemon.where("name = #{}")
  end
end

app/controllers/moves_controller.rb
class MovesController < ApplicationController
  before_action :set_move, only: %i[ show edit update destroy ]

  # GET /moves or /moves.json
  def index
    @moves = Move.order(id: :asc).page(params[:page])
  end

  # GET /moves/1 or /moves/1.json
  def show
  end

  # GET /moves/new
  def new
    @move = Move.new
  end

  # GET /moves/1/edit
  def edit
  end

  # POST /moves or /moves.json
  def create
    @move = Move.new(move_params)

    respond_to do |format|
      if @move.save
        format.html { redirect_to move_url(@move), notice: "Move was successfully created." }
        format.json { render :show, status: :created, location: @move }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @move.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /moves/1 or /moves/1.json
  def update
    respond_to do |format|
      if @move.update(move_params)
        format.html { redirect_to move_url(@move), notice: "Move was successfully updated." }
        format.json { render :show, status: :ok, location: @move }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @move.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moves/1 or /moves/1.json
  def destroy
    @move.destroy

    respond_to do |format|
      format.html { redirect_to moves_url, notice: "Move was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_move
      @move = Move.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def move_params
      params.require(:move).permit(:moveId, :name, :accuracy, :effect, :flavourText)
    end
end

app/controllers/pokemon_types_controller.rb
class PokemonTypesController < ApplicationController
  before_action :set_pokemon_type, only: %i[ show edit update destroy ]

  # GET /pokemon_types or /pokemon_types.json
  def index
    @pokemon_types = PokemonType.all
  end

  # GET /pokemon_types/1 or /pokemon_types/1.json
  def show
  end

  # GET /pokemon_types/new
  def new
    @pokemon_type = PokemonType.new
  end

  # GET /pokemon_types/1/edit
  def edit
  end

  # POST /pokemon_types or /pokemon_types.json
  def create
    @pokemon_type = PokemonType.new(pokemon_type_params)

    respond_to do |format|
      if @pokemon_type.save
        format.html { redirect_to pokemon_type_url(@pokemon_type), notice: "Pokemon type was successfully created." }
        format.json { render :show, status: :created, location: @pokemon_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pokemon_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pokemon_types/1 or /pokemon_types/1.json
  def update
    respond_to do |format|
      if @pokemon_type.update(pokemon_type_params)
        format.html { redirect_to pokemon_type_url(@pokemon_type), notice: "Pokemon type was successfully updated." }
        format.json { render :show, status: :ok, location: @pokemon_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pokemon_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pokemon_types/1 or /pokemon_types/1.json
  def destroy
    @pokemon_type.destroy

    respond_to do |format|
      format.html { redirect_to pokemon_types_url, notice: "Pokemon type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pokemon_type
      @pokemon_type = PokemonType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pokemon_type_params
      params.require(:pokemon_type).permit(:pokemonId, :typeId, :pokemon_id, :type_id)
    end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :set_type, only: %i[ show edit update destroy ]

  # GET /types or /types.json
  def index
    @types = Type.all
  end

  # GET /types/1 or /types/1.json
  def show
  end

  # GET /types/new
  def new
    @type = Type.new
  end

  # GET /types/1/edit
  def edit
  end

  # POST /types or /types.json
  def create
    @type = Type.new(type_params)

    respond_to do |format|
      if @type.save
        format.html { redirect_to type_url(@type), notice: "Type was successfully created." }
        format.json { render :show, status: :created, location: @type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /types/1 or /types/1.json
  def update
    respond_to do |format|
      if @type.update(type_params)
        format.html { redirect_to type_url(@type), notice: "Type was successfully updated." }
        format.json { render :show, status: :ok, location: @type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1 or /types/1.json
  def destroy
    @type.destroy

    respond_to do |format|
      format.html { redirect_to types_url, notice: "Type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type
      @type = Type.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def type_params
      params.require(:type).permit(:typeId, :name)
    end
end

app/helpers/abilities_helper.rb
module AbilitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/moves_helper.rb
module MovesHelper
end

app/helpers/pokemon_moves_helper.rb
module PokemonMovesHelper
end

app/helpers/pokemon_types_helper.rb
module PokemonTypesHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/helpers/sprites_helper.rb
module SpritesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/pokemon_types/_form.html.erb
<%= form_with(model: pokemon_type) do |form| %>
  <% if pokemon_type.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pokemon_type.errors.count, "error") %> prohibited this pokemon_type from being saved:</h2>

      <ul>
        <% pokemon_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :pokemonId, style: "display: block" %>
    <%= form.number_field :pokemonId %>
  </div>

  <div>
    <%= form.label :typeId, style: "display: block" %>
    <%= form.number_field :typeId %>
  </div>

  <div>
    <%= form.label :pokemon_id, style: "display: block" %>
    <%= form.text_field :pokemon_id %>
  </div>

  <div>
    <%= form.label :type_id, style: "display: block" %>
    <%= form.text_field :type_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pokemon_types/_pokemon_type.html.erb
<div id="<%= dom_id pokemon_type %>">
  <p>
    <strong>Pokemonid:</strong>
    <%= pokemon_type.pokemonId %>
  </p>

  <p>
    <strong>Typeid:</strong>
    <%= pokemon_type.typeId %>
  </p>

  <p>
    <strong>Pokemon:</strong>
    <%= pokemon_type.pokemon_id %>
  </p>

  <p>
    <strong>Type:</strong>
    <%= pokemon_type.type_id %>
  </p>

</div>

app/views/pokemon_types/edit.html.erb
<h1>Editing pokemon type</h1>

<%= render "form", pokemon_type: @pokemon_type %>

<br>

<div>
  <%= link_to "Show this pokemon type", @pokemon_type %> |
  <%= link_to "Back to pokemon types", pokemon_types_path %>
</div>

app/views/pokemon_types/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pokemon types</h1>

<div id="pokemon_types">
  <% @pokemon_types.each do |pokemon_type| %>
    <%= render pokemon_type %>
    <p>
      <%= link_to "Show this pokemon type", pokemon_type %>
    </p>
  <% end %>
</div>

<%= link_to "New pokemon type", new_pokemon_type_path %>

app/views/pokemon_types/new.html.erb
<h1>New pokemon type</h1>

<%= render "form", pokemon_type: @pokemon_type %>

<br>

<div>
  <%= link_to "Back to pokemon types", pokemon_types_path %>
</div>

app/views/pokemon_types/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pokemon_type %>

<div>
  <%= link_to "Edit this pokemon type", edit_pokemon_type_path(@pokemon_type) %> |
  <%= link_to "Back to pokemon types", pokemon_types_path %>

  <%= button_to "Destroy this pokemon type", @pokemon_type, method: :delete %>
</div>