config/routes.rb
Rails.application.routes.draw do
  get 'home/about'
  get 'home/index'
  get 'pokemons/search'
  resources :pokemon_moves
  resources :pokemon_abilities
  resources :pokemon_types
  resources :moves
  resources :abilities
  resources :types
  resources :sprites
  resources :pokemons
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/ability.rb
class Ability < ApplicationRecord
  validates :id, :name, :effect, presence: true
  validates :id, :name, uniqueness: true

  has_many :pokemon_abilities
  has_many :pokemon, through: :pokemon_abilities
  paginates_per 25
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/move.rb
class Move < ApplicationRecord
  validates :id, :name, :pp, presence: true
  validates :id, :name, uniqueness: true

  has_many :pokemon_moves
  has_many :pokemon, through: :pokemon_moves

  paginates_per 50
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  validates :id, :name, :baseExperience, :hp, :attack, :defense, :specialAttack, :specialDefense, :speed, :weight, :height, presence: true
  validates :id, :name, uniqueness: true

  has_many :pokemon_types
  has_many :types, through: :pokemon_types

  has_many :pokemon_abilites
  has_many :abilites, through: :pokemon_abilities

  has_many :pokemon_moves
  has_many :moves, through: :pokemon_moves

  paginates_per 25
end

app/models/pokemon_ability.rb
class PokemonAbility < ApplicationRecord
  belongs_to :pokemon
  belongs_to :ability
end

app/models/pokemon_move.rb
class PokemonMove < ApplicationRecord
  belongs_to :pokemon
  belongs_to :move
end

app/models/pokemon_type.rb
class PokemonType < ApplicationRecord
  belongs_to :pokemon
  belongs_to :type
end

app/models/sprite.rb
class Sprite < ApplicationRecord
  belongs_to :pokemon
end

app/models/type.rb
class Type < ApplicationRecord
  validates :id, :name, presence: true
  validates :id, :name, uniqueness: true

  has_many :pokemon_types
  has_many :pokemon, through: :pokemon_types
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
  end

  def index
  end

  def search

  end

  def results
    @results = Pokemon.where("name = #{}")
  end
end

app/controllers/moves_controller.rb
class MovesController < ApplicationController
  before_action :set_move, only: %i[ show edit update destroy ]

  # GET /moves or /moves.json
  def index
    @moves = Move.order(id: :asc).page(params[:page])
  end

  # GET /moves/1 or /moves/1.json
  def show
  end

  # GET /moves/new
  def new
    @move = Move.new
  end

  # GET /moves/1/edit
  def edit
  end

  # POST /moves or /moves.json
  def create
    @move = Move.new(move_params)

    respond_to do |format|
      if @move.save
        format.html { redirect_to move_url(@move), notice: "Move was successfully created." }
        format.json { render :show, status: :created, location: @move }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @move.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /moves/1 or /moves/1.json
  def update
    respond_to do |format|
      if @move.update(move_params)
        format.html { redirect_to move_url(@move), notice: "Move was successfully updated." }
        format.json { render :show, status: :ok, location: @move }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @move.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moves/1 or /moves/1.json
  def destroy
    @move.destroy

    respond_to do |format|
      format.html { redirect_to moves_url, notice: "Move was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_move
      @move = Move.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def move_params
      params.require(:move).permit(:moveId, :name, :accuracy, :effect, :flavourText)
    end
end

app/controllers/sprites_controller.rb
class SpritesController < ApplicationController
  before_action :set_sprite, only: %i[ show edit update destroy ]

  # GET /sprites or /sprites.json
  def index
    @sprites = Sprite.all
  end

  # GET /sprites/1 or /sprites/1.json
  def show
  end

  # GET /sprites/new
  def new
    @sprite = Sprite.new
  end

  # GET /sprites/1/edit
  def edit
  end

  # POST /sprites or /sprites.json
  def create
    @sprite = Sprite.new(sprite_params)

    respond_to do |format|
      if @sprite.save
        format.html { redirect_to sprite_url(@sprite), notice: "Sprite was successfully created." }
        format.json { render :show, status: :created, location: @sprite }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sprite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sprites/1 or /sprites/1.json
  def update
    respond_to do |format|
      if @sprite.update(sprite_params)
        format.html { redirect_to sprite_url(@sprite), notice: "Sprite was successfully updated." }
        format.json { render :show, status: :ok, location: @sprite }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sprite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sprites/1 or /sprites/1.json
  def destroy
    @sprite.destroy

    respond_to do |format|
      format.html { redirect_to sprites_url, notice: "Sprite was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sprite
      @sprite = Sprite.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sprite_params
      params.require(:sprite).permit(:spriteFront, :spriteBack, :spriteShinyFront, :spriteShinyBack, :spriteFemaleShinyFront, :spriteFemaleShinyBack, :spriteFemailBack, :spriteFemaleFront, :pokemon_id)
    end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :set_type, only: %i[ show edit update destroy ]

  # GET /types or /types.json
  def index
    @types = Type.all
  end

  # GET /types/1 or /types/1.json
  def show
  end

  # GET /types/new
  def new
    @type = Type.new
  end

  # GET /types/1/edit
  def edit
  end

  # POST /types or /types.json
  def create
    @type = Type.new(type_params)

    respond_to do |format|
      if @type.save
        format.html { redirect_to type_url(@type), notice: "Type was successfully created." }
        format.json { render :show, status: :created, location: @type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /types/1 or /types/1.json
  def update
    respond_to do |format|
      if @type.update(type_params)
        format.html { redirect_to type_url(@type), notice: "Type was successfully updated." }
        format.json { render :show, status: :ok, location: @type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1 or /types/1.json
  def destroy
    @type.destroy

    respond_to do |format|
      format.html { redirect_to types_url, notice: "Type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type
      @type = Type.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def type_params
      params.require(:type).permit(:typeId, :name)
    end
end

app/helpers/abilities_helper.rb
module AbilitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/moves_helper.rb
module MovesHelper
end

app/helpers/pokemon_moves_helper.rb
module PokemonMovesHelper
end

app/helpers/pokemon_types_helper.rb
module PokemonTypesHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/helpers/sprites_helper.rb
module SpritesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/home/about.html.erb
<h1>About this site</h1>
<br>
<h3>About the Plan</h3>

<p>This site is meant for the intro to rails project in the ADEV-3008 Full Stack Web Development course at Red River College</p>
<br>
<h3>About the Author</h3>

<p>Hello! I'm Cameron Foy, the creator of this site. I am a student of the BIT program at Red River College</p>
<br>
<h3>About the Data</h3>

<p>
The data on this site is provided by <a href="https://pokeapi.co">PokeAPI</a>, a RESTful API that contains information on Pokemon, their Moves, Abilities, Types and much more!<br>
Included below is an ERD of the data that I have pulled from this API and stored in the project DB for learning purposes.
</p>
<br>
<h3>Endpoints / Sources Used</h3>
<p>
https://pokeapi.co/api/v2/pokemon/* - Used to seed the DB with Pokemon / Sprites<br>
https://pokeapi.co/api/v2/ability/* - Used to seed the DB with Abilities<br>
https://pokeapi.co/api/v2/move/* - Used to seed the DB with Moves<br>
https://pokeapi.co/api/v2/type/* - Used to seed the DB with types
</p>
<br>

<%= image_tag "pokemon_on_rails.png", alt: 'Entity Relationship Diagram' %>


<p></p>

app/views/home/index.html.erb
<h1>Welcome to Pokemon on Rails!</h1>
<p>Check out the tabs up top to see the data!</p>

app/views/types/_form.html.erb
<%= form_with(model: type) do |form| %>
  <% if type.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(type.errors.count, "error") %> prohibited this type from being saved:</h2>

      <ul>
        <% type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :typeId, style: "display: block" %>
    <%= form.number_field :id %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/types/_type.html.erb
<div class="col-md border-right">
  <strong>Typeid:</strong>
  <%= type.id %>
</div>

<div class="col-md border-right">
  <strong>Name:</strong>
  <%= type.name %>
</div>

app/views/types/edit.html.erb
<h1>Editing type</h1>

<%= render "form", type: @type %>

<br>

<div>
  <%= link_to "Show this type", @type %> |
  <%= link_to "Back to types", types_path %>
</div>

app/views/types/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Types</h1>

<div id="types" class="container">
  <% @types.each do |type| %>
    <div class="row tab-row">
      <%= render type %>
      <div class="col-sm showcol">
        <%= link_to "Show this type", type %>
      </div>
    </div>
  <% end %>
</div>

<%= link_to "New type", new_type_path %>

app/views/types/new.html.erb
<h1>New type</h1>

<%= render "form", type: @type %>

<br>

<div>
  <%= link_to "Back to types", types_path %>
</div>

app/views/types/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">
  <div class="row tab-row">
    <%= render @type %>
  </div>
</div>

<div>
  <%= link_to "Edit this type", edit_type_path(@type) %> |
  <%= link_to "Back to types", types_path %>

  <%= button_to "Destroy this type", @type, method: :delete %>
</div>