config/routes.rb
Rails.application.routes.draw do
  get 'home/about'
  get 'home/index'
  get 'pokemons/search'
  resources :pokemon_moves
  resources :pokemon_abilities
  resources :pokemon_types
  resources :moves
  resources :abilities
  resources :types
  resources :sprites
  resources :pokemons
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/ability.rb
class Ability < ApplicationRecord
  validates :id, :name, :effect, presence: true
  validates :id, :name, uniqueness: true

  has_many :pokemon_abilities
  has_many :pokemon, through: :pokemon_abilities
  paginates_per 25
end

app/controllers/abilities_controller.rb
class AbilitiesController < ApplicationController
  before_action :set_ability, only: %i[ show edit update destroy ]

  # GET /abilities or /abilities.json
  def index
    @abilities = Ability.order(id: :asc).page(params[:page])
  end

  # GET /abilities/1 or /abilities/1.json
  def show
  end

  # GET /abilities/new
  def new
    @ability = Ability.new
  end

  # GET /abilities/1/edit
  def edit
  end

  # POST /abilities or /abilities.json
  def create
    @ability = Ability.new(ability_params)

    respond_to do |format|
      if @ability.save
        format.html { redirect_to ability_url(@ability), notice: "Ability was successfully created." }
        format.json { render :show, status: :created, location: @ability }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ability.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /abilities/1 or /abilities/1.json
  def update
    respond_to do |format|
      if @ability.update(ability_params)
        format.html { redirect_to ability_url(@ability), notice: "Ability was successfully updated." }
        format.json { render :show, status: :ok, location: @ability }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ability.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /abilities/1 or /abilities/1.json
  def destroy
    @ability.destroy

    respond_to do |format|
      format.html { redirect_to abilities_url, notice: "Ability was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ability
      @ability = Ability.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ability_params
      params.require(:ability).permit(:abilityId, :name, :effect, :flavourText)
    end
end

app/helpers/abilities_helper.rb
module AbilitiesHelper
end

app/views/abilities/_ability.html.erb
<div class="col border-right">
  <strong>Abilityid:</strong>
  <%= ability.id %>
</div>

<div class="col border-right">
  <strong>Name:</strong>
  <%= ability.name %>
</div>

<div class="col border-right">
  <strong>Effect:</strong>
  <%= ability.effect %>
</div>

app/views/abilities/_form.html.erb
<%= form_with(model: ability) do |form| %>
  <% if ability.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(ability.errors.count, "error") %> prohibited this ability from being saved:</h2>

      <ul>
        <% ability.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :abilityId, style: "display: block" %>
    <%= form.number_field :id %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :effect, style: "display: block" %>
    <%= form.text_field :effect %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/abilities/edit.html.erb
<h1>Editing ability</h1>

<%= render "form", ability: @ability %>

<br>

<div>
  <%= link_to "Show this ability", @ability %> |
  <%= link_to "Back to abilities", abilities_path %>
</div>

app/views/abilities/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Abilities</h1>
<%= paginate @abilities%>

<%= page_entries_info @abilities %>

<div id="abilities" class="container">
  <% @abilities.each do |ability| %>
  <div class="row tab-row">
    <%= render ability %>
    <div class="col showcol">
      <%= link_to "Show this ability", ability %>
    </div>
  </div>
  <% end %>
</div>

<%= link_to "New ability", new_ability_path %>

app/views/abilities/new.html.erb
<h1>New ability</h1>

<%= render "form", ability: @ability %>

<br>

<div>
  <%= link_to "Back to abilities", abilities_path %>
</div>

app/views/abilities/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">
  <div class="row tab-row">
    <%= render @ability %>
  </div>
</div>

<div>
  <%= link_to "Edit this ability", edit_ability_path(@ability) %> |
  <%= link_to "Back to abilities", abilities_path %>

  <%= button_to "Destroy this ability", @ability, method: :delete %>
</div>