config/routes.rb
Rails.application.routes.draw do
  get 'home/about'
  get 'home/index'
  get 'pokemons/search'
  resources :pokemon_moves
  resources :pokemon_abilities
  resources :pokemon_types
  resources :moves
  resources :abilities
  resources :types
  resources :sprites
  resources :pokemons
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/pokemon_move.rb
class PokemonMove < ApplicationRecord
  belongs_to :pokemon
  belongs_to :move
end

app/controllers/pokemon_moves_controller.rb
class PokemonMovesController < ApplicationController
  before_action :set_pokemon_move, only: %i[ show edit update destroy ]

  # GET /pokemon_moves or /pokemon_moves.json
  def index
    @pokemon_moves = PokemonMove.all
  end

  # GET /pokemon_moves/1 or /pokemon_moves/1.json
  def show
  end

  # GET /pokemon_moves/new
  def new
    @pokemon_move = PokemonMove.new
  end

  # GET /pokemon_moves/1/edit
  def edit
  end

  # POST /pokemon_moves or /pokemon_moves.json
  def create
    @pokemon_move = PokemonMove.new(pokemon_move_params)

    respond_to do |format|
      if @pokemon_move.save
        format.html { redirect_to pokemon_move_url(@pokemon_move), notice: "Pokemon move was successfully created." }
        format.json { render :show, status: :created, location: @pokemon_move }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pokemon_move.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pokemon_moves/1 or /pokemon_moves/1.json
  def update
    respond_to do |format|
      if @pokemon_move.update(pokemon_move_params)
        format.html { redirect_to pokemon_move_url(@pokemon_move), notice: "Pokemon move was successfully updated." }
        format.json { render :show, status: :ok, location: @pokemon_move }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pokemon_move.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pokemon_moves/1 or /pokemon_moves/1.json
  def destroy
    @pokemon_move.destroy

    respond_to do |format|
      format.html { redirect_to pokemon_moves_url, notice: "Pokemon move was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pokemon_move
      @pokemon_move = PokemonMove.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pokemon_move_params
      params.require(:pokemon_move).permit(:pokemonId, :moveId, :pokemon_id, :move_id)
    end
end

app/helpers/pokemon_moves_helper.rb
module PokemonMovesHelper
end

app/views/pokemon_moves/_form.html.erb
<%= form_with(model: pokemon_move) do |form| %>
  <% if pokemon_move.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pokemon_move.errors.count, "error") %> prohibited this pokemon_move from being saved:</h2>

      <ul>
        <% pokemon_move.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :pokemonId, style: "display: block" %>
    <%= form.number_field :pokemonId %>
  </div>

  <div>
    <%= form.label :moveId, style: "display: block" %>
    <%= form.number_field :moveId %>
  </div>

  <div>
    <%= form.label :pokemon_id, style: "display: block" %>
    <%= form.text_field :pokemon_id %>
  </div>

  <div>
    <%= form.label :move_id, style: "display: block" %>
    <%= form.text_field :move_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pokemon_moves/_pokemon_move.html.erb
<div id="<%= dom_id pokemon_move %>">
  <p>
    <strong>Pokemonid:</strong>
    <%= pokemon_move.pokemonId %>
  </p>

  <p>
    <strong>Moveid:</strong>
    <%= pokemon_move.moveId %>
  </p>

  <p>
    <strong>Pokemon:</strong>
    <%= pokemon_move.pokemon_id %>
  </p>

  <p>
    <strong>Move:</strong>
    <%= pokemon_move.move_id %>
  </p>

</div>

app/views/pokemon_moves/edit.html.erb
<h1>Editing pokemon move</h1>

<%= render "form", pokemon_move: @pokemon_move %>

<br>

<div>
  <%= link_to "Show this pokemon move", @pokemon_move %> |
  <%= link_to "Back to pokemon moves", pokemon_moves_path %>
</div>

app/views/pokemon_moves/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pokemon moves</h1>

<div id="pokemon_moves">
  <% @pokemon_moves.each do |pokemon_move| %>
    <%= render pokemon_move %>
    <p>
      <%= link_to "Show this pokemon move", pokemon_move %>
    </p>
  <% end %>
</div>

<%= link_to "New pokemon move", new_pokemon_move_path %>

app/views/pokemon_moves/new.html.erb
<h1>New pokemon move</h1>

<%= render "form", pokemon_move: @pokemon_move %>

<br>

<div>
  <%= link_to "Back to pokemon moves", pokemon_moves_path %>
</div>

app/views/pokemon_moves/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pokemon_move %>

<div>
  <%= link_to "Edit this pokemon move", edit_pokemon_move_path(@pokemon_move) %> |
  <%= link_to "Back to pokemon moves", pokemon_moves_path %>

  <%= button_to "Destroy this pokemon move", @pokemon_move, method: :delete %>
</div>